"""
Lambda — Async WeatherAPI Ingestion
Fetches weather data for a batch of locations and dates, writes to S3 raw zone.

Key design decisions:
- aiohttp for async HTTP — 30 concurrent requests (empirically determined limit
  that respects WeatherAPI rate limits AND Lambda 15-min timeout)
- One output file per location_id (not per request) — avoids micro-file problem
  that would degrade Glue PySpark performance
- Deterministic S3 keys — safe to re-run on Lambda retry without duplicates
"""

import asyncio
import json
import logging
import os
from datetime import datetime, timedelta

import aiohttp
import boto3

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

S3_BUCKET       = os.environ["S3_BUCKET"]
WEATHERAPI_BASE = "https://api.weatherapi.com/v1/history.json"
MAX_CONCURRENCY = 30          # Empirically validated: safe limit for WeatherAPI + Lambda timeout
s3_client       = boto3.client("s3")


# ── Batch metadata ─────────────────────────────────────────────────────────

def load_batch_metadata(batch_id: str) -> dict:
    """Load batch JSON from S3 — generated by Airflow's generate_batches task."""
    key = f"staging/batch_{batch_id}.json"
    response = s3_client.get_object(Bucket=S3_BUCKET, Key=key)
    return json.loads(response["Body"].read())


# ── Async fetching ─────────────────────────────────────────────────────────

async def fetch_single(
    session: aiohttp.ClientSession,
    api_token: str,
    location_id: str,
    date: str,
    semaphore: asyncio.Semaphore,
) -> dict | None:
    """Fetch one location/date pair. Semaphore limits concurrency."""
    async with semaphore:
        params = {"key": api_token, "q": location_id, "dt": date}
        try:
            async with session.get(WEATHERAPI_BASE, params=params, timeout=aiohttp.ClientTimeout(total=30)) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    data["_location_id"] = location_id
                    data["_date"]        = date
                    return data
                else:
                    logger.warning("WeatherAPI %s for location=%s date=%s", resp.status, location_id, date)
                    return None
        except asyncio.TimeoutError:
            logger.error("Timeout: location=%s date=%s", location_id, date)
            return None


async def fetch_batch(
    api_token: str,
    location_ids: list[str],
    start_date: str,
    end_date: str,
) -> dict[str, list[dict]]:
    """
    Fetch all (location, date) pairs in the batch concurrently.
    Results are grouped by location_id to write one S3 file per location —
    avoiding micro-files that degrade Glue PySpark read performance.
    """
    semaphore = asyncio.Semaphore(MAX_CONCURRENCY)
    date_range = _date_range(start_date, end_date)
    results_by_location: dict[str, list[dict]] = {loc: [] for loc in location_ids}

    async with aiohttp.ClientSession() as session:
        tasks = [
            fetch_single(session, api_token, loc, date, semaphore)
            for loc in location_ids
            for date in date_range
        ]
        responses = await asyncio.gather(*tasks, return_exceptions=False)

    for resp in responses:
        if resp:
            results_by_location[resp["_location_id"]].append(resp)

    return results_by_location


def _date_range(start: str, end: str) -> list[str]:
    start_dt = datetime.strptime(start, "%Y-%m-%d")
    end_dt   = datetime.strptime(end,   "%Y-%m-%d")
    return [
        (start_dt + timedelta(days=i)).strftime("%Y-%m-%d")
        for i in range((end_dt - start_dt).days + 1)
    ]


# ── S3 write ───────────────────────────────────────────────────────────────

def write_location_to_s3(location_id: str, records: list[dict], execution_date: str) -> None:
    """
    Write all records for one location as a single JSON lines file.
    Key is deterministic — same location + execution_date always produces the same key.
    Guarantees S3 write is idempotent on Lambda retry.
    """
    if not records:
        return

    key  = f"raw/{execution_date.replace('-', '/')}/location={location_id}/data.json"
    body = "\n".join(json.dumps(r) for r in records)

    s3_client.put_object(
        Bucket      = S3_BUCKET,
        Key         = key,
        Body        = body.encode("utf-8"),
        ContentType = "application/json",
    )
    logger.info("Wrote %d records → s3://%s/%s", len(records), S3_BUCKET, key)


# ── Handler ────────────────────────────────────────────────────────────────

def handler(event: dict, context) -> dict:
    """
    event: {
      "api_token": "...",        # WeatherAPI key (from Secrets Manager via Airflow)
      "batch_id":  "...",        # Batch metadata file ID in S3
      "execution_date": "YYYY-MM-DD"
    }
    """
    api_token      = event["api_token"]
    batch_id       = event["batch_id"]
    execution_date = event["execution_date"]

    logger.info("Processing batch_id=%s execution_date=%s", batch_id, execution_date)

    batch         = load_batch_metadata(batch_id)
    location_ids  = batch["location_ids"]
    start_date    = batch["start_date"]
    end_date      = batch["end_date"]

    total_points  = len(location_ids) * len(_date_range(start_date, end_date))
    logger.info("Batch: %d locations × %s→%s = %d data points",
                len(location_ids), start_date, end_date, total_points)

    # Run async fetch
    results = asyncio.run(fetch_batch(api_token, location_ids, start_date, end_date))

    # Write one file per location
    written = 0
    for location_id, records in results.items():
        write_location_to_s3(location_id, records, execution_date)
        written += len(records)

    return {
        "status":          "success",
        "batch_id":        batch_id,
        "locations":       len(location_ids),
        "records_written": written,
    }
